### ISSUE TITLE
[ubuntu][windows][bug/question] Where is the ack bniary

### ISSUE THREAD

**Issue by Fabrizio-Caruso** [davidgiven/ack#113]
I have managed to install Ubuntu on Windows 10
I have installed all necessary deps for ACK
I have managed to build ACK with just:
make
make install
(no evident errors)
and no other settings.
After completion, I do not find the ack binary.
It is not in /usr/local as expected

make install displayed:
```
[sudo] password for brizio:
mkdir -p /tmp/ack-build/staging
tar cf - -C /tmp/ack-build/staging . | tar xvf - -C /tmp/ack-build/staging
./
./bin/
./bin/aal
./bin/abmodules
./bin/ack
tar: ./bin/ack: file changed as we read it
./bin/aelflod
./bin/anm
./bin/ashow
./bin/asize
./bin/aslod
tar: ./bin: file changed as we read it
....
```
and no error message.

**Comment by Fabrizio-Caruso** [comment]
I found it inside /tmp...
Maybe this is wrong? Isn't it?

**Comment by davidgiven** [comment]
It needs to be configured --- edit the Makefile as per the instructions and change the definition of PREFIX at the top.

The default should actually be /usr/local, and it got set to `$(INSDIR)` by accident --- I've fixed this.

**Comment by davidgiven** [comment]
(Fixed in 1d9f9074d990e2c6bbe59cf7193a8c4fdf58ad35)

**Comment by drawkula** [comment]
So now...

    make INSDIR=/opt/ack

...won't work any more and changes in the `Makefile` are needed? That may need to be undone before the next `git pull` or needs `git stash` or working in a local branch and sure somewhen that will raise questions too. Wouldn't documenting how to pass `INSDIR=somepath` to the build process have been the easier way?

**Comment by davidgiven** [comment]
INSDIR isn't the final installation directory --- it's a temporary directory used _during compilation_. The files are only copied to PREFIX once the compilation is done.

PREFIX was set to INSDIR by accident, as I mostly don't bother to install the final compiler during development and just run it out of the build temporary directory, and so having PREFIX set there is convenient so I don't have to override the library path using an environment variable.

**Comment by Fabrizio-Caruso** [comment]
@drawkula, after a second rebuild with "make INSDIR=/opt/ack" I still get the error
"
brizio@DESKTOP-I20P8HM:/mnt/c/Retro/ACK/ack$ ack -cpm -O /mnt/c/Retro/ACK/ack/examples/paranoia.c
ack: -c flag has invalid tail
"

**Comment by Fabrizio-Caruso** [comment]
My mistake, it does work!

**Comment by drawkula** [comment]
After the latest changes it would be:

    make PREFIX=/opt/ack
    make PREFIX=/opt/ack install

Done here a few minutes ago on Debian9.
And compiled stuff runs (tested with a C mandelbrot program for CP/M).
