### ISSUE TITLE
[bug/question] Cannot compile any example

### ISSUE THREAD

**Issue by Fabrizio-Caruso** [davidgiven/ack#114]
```
brizio@DESKTOP-I20P8HM:/usr/local/ack-build$ ./staging/bin/ack -mlinux386 -O /mnt/c/Retro/ACK/ack/examples/paranoia.c
./staging/bin/ack: Cannot find description for fe
```

```
brizio@DESKTOP-I20P8HM:/usr/local/ack-build$ ./staging/bin/ack -cpm -O /mnt/c/Retro/ACK/ack/examples/paranoia.c
./staging/bin/ack: -c flag has invalid tail
```

**Comment by davidgiven** [comment]
It's looking for its data files in the wrong place because the PREFIX in the makefile wasn't set correctly. This should have had a better default to avoid this kind of confusion, and I've fixed it; please try again.

**Comment by Fabrizio-Caruso** [comment]
Do I need to re-build? or just git pull + make install?

**Comment by davidgiven** [comment]
Rebuild, I'm afraid (the paths end up baked into the binaries).

**Comment by Fabrizio-Caruso** [comment]
I just rebuilt with "sudo make INSDIR=opt/ack" as suggested.
Then "sudo make install" but I still get:
"
brizio@DESKTOP-I20P8HM:/mnt/c/Retro/ACK/ack$ ack -cpm -O /mnt/c/Retro/ACK/ack/examples/paranoia.c
ack: -c flag has invalid tail
"

What should I do exactly to get ack installed and how to call it?

**Comment by Fabrizio-Caruso** [comment]
Can I simply do if I am happy with a default destination?
make clean
make 
sudo make install

Now, does "make install" place the binary in /opt/local (as in the doc) ?
Has this been fixed?

**Comment by Fabrizio-Caruso** [comment]
It does work! :-)

**Comment by davidgiven** [comment]
`-cpm` isn't a valid flag; it thinks you've used `-c` and told it to generate `pm` intermediate files. To use the CP/M code generator, use `-mcpm` instead.
